os: linux
language: minimal
services:
  - docker

jobs:
  include:
    - name: "tests"
      script:
        - docker run -v `pwd`:`pwd` -w `pwd` -t rusdevops/bootstrap-cpp tests/tests.sh

notifications:
  email: false